version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing pysam
          command: |
            Installing pysam
            pysam setup.py install --user
