version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Installing pysam
          command: |
            echo Installing pysam
            python setup.py install --user
      - run:
          name: Testing reading encrypted BGZF
          command: |
            echo Retrieving public and private keys library
            export HTS_KEYS="../tests/crypto_read/hts-keys.txt"
            echo Running python script
            python ../tests/crypto_read.py
