version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "26:d5:68:e5:7c:54:20:f8:95:9c:60:2d:34:cc:bc:eb"
      - run:
          name: Setting up environment
          command: |
            echo Install OpenSSL C library
            sudo apt-get install libssl-dev
            sudo apt-get install openssl
            sudo apt-get install libcurl4-openssl-dev
            gcc --version
            sudo apt-get install build-essential
          name: Installing pysam
          command: |
            echo Installing pysam
            python setup.py install --user
      - run:
          name: Testing reading encrypted BGZF
          command: |
            cd tests
            echo Retrieving public and private keys library
            export HTS_KEYS="crypto_read/hts-keys.txt"
            echo Running python script
            python crypto_read.py
