version: 2
jobs:
  machine:
    pre:
      - pyenv local 2.7.0
      - virtualenv venv
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing pysam
          command: |
            echo Installing pysam
            python setup.py install --user
