version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Enable SSH
          command: |
            ssh git@github.com
      - run:
          name: Setting up environment
          command: |
            echo Installing pysam
            python setup.py install --user
            echo Install OpenSSL C library
            sudo apt-get install libssl-dev
            sudo apt-get install openssl
      - run:
          name: Testing reading encrypted BGZF
          command: |
            cd tests
            echo Retrieving public and private keys library
            export HTS_KEYS="crypto_read/hts-keys.txt"
            echo Running python script
            python crypto_read.py
