version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3a:67:ef:a3:be:a2:70:b2:95:f7:91:58:57:e7:34:27"
      - run:
          name: Setting up environment
          command: |
            echo Installing pysam
            python setup.py install --user
            echo Install OpenSSL C library
            sudo apt-get install libssl-dev
            sudo apt-get install openssl
      - run:
          name: Testing reading encrypted BGZF
          command: |
            cd tests
            echo Retrieving public and private keys library
            export HTS_KEYS="crypto_read/hts-keys.txt"
            echo Running python script
            python crypto_read.py
